# flag which determines the goal type
bool relative

geometry_msgs/Point rel_goal_position
geographic_msgs/GeoPoint abs_goal_position

---
# Result definition
bool success
string message

---
# Feedback: current GPS position
geographic_msgs/GeoPoint curr_position
